1. Importer numpy

In [1]:
import numpy as np

2. Creer un vecteur de 10 valeurs nulles 

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
a=np.zeros(10)
a[5]=1
a

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [33]:
rg=np.random.default_rng(1)
rg.normal(20,3,10)

array([21.03675258, 22.46485443, 20.99131123, 16.09052831, 22.7160676 ,
       21.33912372, 18.38914029, 21.74335431, 21.09371719, 20.88239749])

In [34]:
rg2=np.random.default_rng(2)
rg2.normal(20,3,10)

array([20.56716015, 18.43175468, 18.76080937, 12.67559785, 25.39912215,
       23.43249762, 19.02373149, 22.32141976, 20.84363201, 18.33853149])