#Importation de Numpy

In [2]:
import numpy as np

#Instruction simple

In [4]:
x=2

In [5]:
y=3

In [6]:
x+y

5

Creation d'une liste

In [9]:
my_list=[1,2,3]

In [10]:
type(my_list)

list

Conversion en tableau numpy

In [11]:
np.array(my_list)

array([1, 2, 3])

In [12]:
my_list

[1, 2, 3]

In [13]:
my_arr=np.array(my_list)

Type d'un tableau numpy : Tableau à n dimensions

In [14]:
type(my_arr)

numpy.ndarray

Creons a present une matrice (tableau à 2 dimensios) avec les listes standard 

In [15]:
my_matrix=[[1,2,3],[2,5,6],[7,8,9]]

In [16]:
my_matrix

[[1, 2, 3], [2, 5, 6], [7, 8, 9]]

On converti à présent cette matrice en tableau numpy à 2 dimensions

In [17]:
np_matrix=np.array(my_matrix)

In [18]:
np_matrix

array([[1, 2, 3],
       [2, 5, 6],
       [7, 8, 9]])

Noter que numpy sait déjà qu'il sagit d'un tableau de dimension 2. Cela va permettre à numpy de manipuler des tableaux de données et appliquer des fonctions sur des dataset bidimensionnels 

#Regardons une fonction de la bibilothèque Numpy et voyons comment numpy manipules les données. Cette fonction est l'équivalent de range de python

In [24]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [28]:
#On peut aussi avoir besoin de manipuler un tableau de zero dans ce cas 
np.zeros(10)
#On remarque que ces valeurs sont des flottants 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#On peut aussi avoir envie d'avoir une matrice de zero dans ce cas le parametre shape sera un tuple (nb lignes,nb colones)

In [32]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
#Pareil on a aussi la fonction np.ones qui retourne un tableau de 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [40]:
#La fonction linespace permet elle aussi de générer des tableaux numpy
np.linspace(0,10,20)
#On obtient 20 nombre uniformement espacé entre 0 inclus et 10 inclus

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [42]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
I=np.eye(3)

In [48]:
M=np_matrix**2-5*I

In [49]:
M

array([[-4.,  4.,  9.],
       [ 4., 20., 36.],
       [49., 64., 76.]])

In [50]:
A=[[0,0,15],[1,0,-17],[0,1,7]]

In [51]:
A=np.array(A)

In [52]:
A

array([[  0,   0,  15],
       [  1,   0, -17],
       [  0,   1,   7]])

In [112]:
M=A@A-4*A+5*I

In [113]:
M

array([[  5.,  15.,  45.],
       [ -4., -12., -36.],
       [  1.,   3.,   9.]])

In [160]:
B=A
BA
B

array([[   0,   15,  105],
       [   0,  -17, -104],
       [   1,    7,   32]])

#Renvoie un nombre aléatoire compris entre 0 et 1 suivant la distribution uniforme

In [64]:
np.random.rand(1)

array([0.10388043])

In [66]:
np.random.rand(3,2)

array([[0.41309814, 0.71860117],
       [0.86595014, 0.59338698],
       [0.12249315, 0.91411087]])

#Si par contre on veut des valeurs suivant une distribution normale on fait

In [65]:
np.random.randn(2)

array([-0.98987741, -0.43557042])

In [67]:
np.random.randn(3,4)

array([[-1.0848926 , -2.03259473, -0.21979255, -2.38443023],
       [-0.86030832, -0.16774671, -1.17020112,  2.3957831 ],
       [ 1.65399984,  1.51483397,  0.25391545, -0.41301593]])

#Si on veut des nombres entiers aléatoires entre deux valeurs

In [70]:
np.random.randint(1,5,(3,3))

array([[4, 4, 4],
       [3, 1, 1],
       [2, 2, 3]])

In [71]:
np.random.randint(1,5,3)

array([4, 4, 3])

In [73]:
np.random.randint(0,101,(3,3))

array([[95, 42,  1],
       [12, 67, 17],
       [85, 47, 79]])

#Le seed permet de reproduire un état aléatoire dans le quel les données aléatoires peuvent etre reproduite

#Le seed permet de repeter des distributions aléatoires afin de tester différents modèles ou méthodes de visualisation

#Test d'un état aléatoire avec seed

In [87]:
np.random.seed(237)
np.random.randint(1,10,9)

array([3, 4, 1, 9, 5, 8, 6, 1, 2])

Que se passe t-il si on sépare le seed de la demande de nombre aléatoire

In [83]:
np.random.seed(237)

In [89]:
np.random.randint(1,10,9)

array([5, 5, 6, 2, 4, 6, 9, 9, 9])

In [162]:
arr=np.arange(0,25)

In [163]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [92]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [93]:
arr2=np.random.randint(0,101,10)

In [94]:
arr2

array([51, 98, 69, 10, 54, 96, 90, 10, 84,  3])

In [95]:
arr2.max()

98

In [96]:
arr2.min()

3

In [97]:
arr2.argmax()

1

In [98]:
arr2.argmin()

9

In [99]:
arr2.dtype

dtype('int32')

In [100]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [101]:
arr.shape

(25,)

In [102]:
arr = arr.reshape(5,5)

In [103]:
arr.shape

(5, 5)

Ma méthode reshape permet d'avoir des tableaux de dimension 2 par ligne ou par colonne 

In [104]:
arr[2:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [105]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [106]:
arr[2]

array([10, 11, 12, 13, 14])

In [108]:
arr[2:,::2]

array([[10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

In [109]:
arr[::2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [110]:
np.nan

nan

In [111]:
0*np.nan

nan

In [139]:
a=np.arange(10,dtype=np.int64)**3

In [118]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int64)

In [140]:
a[2]

8

In [120]:
a[2:5]

array([ 8, 27, 64], dtype=int64)

In [141]:
a[:2]

array([0, 1], dtype=int64)

In [142]:
np.floor(a)

array([  0.,   1.,   8.,  27.,  64., 125., 216., 343., 512., 729.])

In [143]:
b=list()
for i in range(10):
    b+=[np.random.normal()]

In [144]:
b

[-0.5880887566851704,
 0.6955824136520657,
 -2.2596312495079633,
 1.460160633612059,
 0.1119867777841333,
 -0.09129315575705632,
 0.18032263093115075,
 0.09997071907433226,
 1.9830257205116466,
 0.17100135667840966]

In [145]:
b_new=np.array(b)

In [146]:
b_new.dtype

dtype('float64')

Pour combiner 2 liste de même structure on utilise hstack (en colone) et vstack (en ligne)

In [152]:
np.hstack((a,b_new)).shape

(20,)

In [155]:
np.hstack((a,b_new))

array([ 0.00000000e+00,  1.00000000e+00,  8.00000000e+00,  2.70000000e+01,
        6.40000000e+01,  1.25000000e+02,  2.16000000e+02,  3.43000000e+02,
        5.12000000e+02,  7.29000000e+02, -5.88088757e-01,  6.95582414e-01,
       -2.25963125e+00,  1.46016063e+00,  1.11986778e-01, -9.12931558e-02,
        1.80322631e-01,  9.99707191e-02,  1.98302572e+00,  1.71001357e-01])

In [154]:
np.vstack((a,b_new)).shape

(2, 10)

In [156]:
np.vstack((a,b_new))

array([[ 0.00000000e+00,  1.00000000e+00,  8.00000000e+00,
         2.70000000e+01,  6.40000000e+01,  1.25000000e+02,
         2.16000000e+02,  3.43000000e+02,  5.12000000e+02,
         7.29000000e+02],
       [-5.88088757e-01,  6.95582414e-01, -2.25963125e+00,
         1.46016063e+00,  1.11986778e-01, -9.12931558e-02,
         1.80322631e-01,  9.99707191e-02,  1.98302572e+00,
         1.71001357e-01]])

In [164]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [166]:
arr=arr.reshape((5,5))

In [167]:
for row in arr:
    print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]


flat est pour pouvoir utiliser les valeur d'un tableau séparement

In [169]:
for row in arr.flat:
    print(row)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [170]:
a is b

False

In [171]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int64)

In [172]:
b

[-0.5880887566851704,
 0.6955824136520657,
 -2.2596312495079633,
 1.460160633612059,
 0.1119867777841333,
 -0.09129315575705632,
 0.18032263093115075,
 0.09997071907433226,
 1.9830257205116466,
 0.17100135667840966]

In [173]:
b=a

In [174]:
a is b

True