Importation de numpy

In [1]:
import numpy as np

Creation d'un tableau numpy avec la methode arange

In [2]:
arr=np.arange(0,10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Indexation dans un tableau

In [4]:
arr[3]

3

In [5]:
arr[3:7]

array([3, 4, 5, 6])

In [6]:
arr[3:8]

array([3, 4, 5, 6, 7])

In [7]:
arr.size

10

In [10]:
arr[-2]

8

In [12]:
arr[3:10]

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
arr[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [15]:
arr[:5]

array([0, 1, 2, 3, 4])

In [18]:
arr[0:10:2]

array([0, 2, 4, 6, 8])

In [20]:
tab=arr%2==0

In [21]:
arr[tab]

array([0, 2, 4, 6, 8])

In [22]:
arr[arr%2==0]

array([0, 2, 4, 6, 8])

In [24]:
arr2=np.arange(1,10).reshape(3,3)

In [25]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
a=np.array([1,2,0])
b=np.array([2,1,1])
tab=arr2[a,b]

In [28]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
tab*=2

In [42]:
tab

array([12, 16,  4])

In [43]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
tab2=arr[::2]

In [48]:
tab2=tab2*tab2

In [49]:
tab2

array([ 0,  4, 16, 36, 64])

In [50]:
arr

array([ 0,  1,  4,  3, 16,  5, 36,  7, 64,  9])

0x0
2x2
4x4
6x6
8x8

In [70]:
liste=[1,2,3,4]
liste2=[]
for i in liste:
    liste2+=[i*i]
liste=liste2

In [73]:
liste=liste2

In [75]:
liste*=liste

TypeError: can't multiply sequence by non-int of type 'list'

Selection dans un tableau Numpy

In [60]:
arr2[arr2>4]

array([5, 6, 7, 8, 9])

In [61]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
arr2.mean()

5.0

In [63]:
arr2[arr2>arr2.mean()]

array([6, 7, 8, 9])

In [64]:
np.random.seed(1)
alea=np.random.randn(20)

In [65]:
alea

array([ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763,
       -2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038,
        1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944,
       -1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521])

In [66]:
alea.mean()

-0.1333646364607294

In [81]:
alea2=(alea-alea.mean())/alea.std()

In [80]:
alea2.std()

1.0

In [82]:
A=np.random.randint(0,10,(4,4))

In [83]:
A

array([[4, 8, 1, 4],
       [0, 3, 9, 2],
       [0, 4, 9, 2],
       [7, 7, 9, 8]])

In [91]:
for i in A.flat:
    if(i>5):
        print(i)

8
9
9
7
7
9
8


In [95]:
for i in A[A>5].flat:
    print(i)

8
9
9
7
7
9
8


In [96]:
type(A)

numpy.ndarray

In [104]:
arr.max()

64

In [101]:
arr

array([ 0,  1,  4,  3, 16,  5, 36,  7, 64,  9])

In [106]:
arr.sum()/arr.size

14.5

In [107]:
arr.mean()

14.5

In [110]:
pip help


Usage:   
  C:\Users\Huawei\anaconda3\envs\MasterClassDS-ML\python.exe -m pip <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  inspect                     Inspect the python environment.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible dependencies.
  config                      Manage local and global configuration.
  search                      Search PyPI for packages.
  cache                       Inspect and manage pip's wheel cache.
  index                       Inspect information available from package indexes.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes 

In [111]:
pip -v


Usage:   
  C:\Users\Huawei\anaconda3\envs\MasterClassDS-ML\python.exe -m pip <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  inspect                     Inspect the python environment.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible dependencies.
  config                      Manage local and global configuration.
  search                      Search PyPI for packages.
  cache                       Inspect and manage pip's wheel cache.
  index                       Inspect information available from package indexes.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes 

In [2]:
mat = np.arange(1,26).reshape(5,5)

In [3]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [5]:
mat[[1,2,0],[0,3,1]]

array([ 6, 14,  2])

In [8]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [10]:
mat[-1,:]

array([21, 22, 23, 24, 25])

In [13]:
mat[mat%2==0].reshape(3,4)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])