Partie A

In [13]:
#1
import numpy as np

In [14]:
#2
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
#3
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [51]:
#4
#np.ones(10)*5
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [17]:
#5
np.arange(10,71)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70])

In [18]:
#6
np.arange(10,71,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70])

In [19]:
#7
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
#8
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
#9
np.random.rand()

0.618955820433825

In [22]:
#10
np.random.randn(25)

array([-0.64454751, -0.32174637,  0.94131795,  0.02033997,  1.58692792,
        1.32648755, -0.48173805, -1.29366592, -0.23142112,  0.2801508 ,
       -0.81145847,  0.35877155, -0.3225394 ,  0.98879258, -2.08127592,
        0.9751056 , -1.61478307,  0.65940072, -1.40976666, -1.87087998,
       -0.43237183, -0.60014646, -0.46682847, -0.25085077, -0.37586885])

In [24]:
#11
np.random.normal(20,5,25)

array([15.42102328, 27.88620064, 22.10644746, 18.5021852 , 26.6219799 ,
       21.71664802, 20.99233782, 21.90869101, 13.86557095, 16.52764745,
       17.30868586, 16.86947204, 25.37658744, 23.43792119, 23.5545212 ,
       23.86479842, 20.22250254, 18.92079164, 19.66132254, 26.65849165,
       30.43734645, 13.59268827, 15.84251306, 25.63149169, 22.67686176])

In [25]:
#12
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

Partie B

In [27]:
#1
mat = np.arange(1,26).reshape(5,5)

In [28]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [29]:
#2
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [31]:
#3
mat[[1,2,0],[0,3,1]]

array([ 6, 14,  2])

In [54]:
#4
mat[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [33]:
#5
mat[-1]

array([21, 22, 23, 24, 25])

In [55]:
#5
mat[4]

array([21, 22, 23, 24, 25])

In [36]:
#6
mat[mat>mat.mean()]

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [38]:
mat[mat%2==0].reshape(3,4)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

Partie C

In [44]:
#1
mat.sum()

325

In [57]:
#2
np.round(mat.std(),2)

7.21

In [46]:
#3
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [47]:
#4
mat.mean(axis=1)

array([ 3.,  8., 13., 18., 23.])

In [48]:
#5
mat@mat.T

array([[  55,  130,  205,  280,  355],
       [ 130,  330,  530,  730,  930],
       [ 205,  530,  855, 1180, 1505],
       [ 280,  730, 1180, 1630, 2080],
       [ 355,  930, 1505, 2080, 2655]])

In [49]:
mat.T

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [50]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [58]:
mat*mat

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]])